version: '3.8'

services:
  # Service Frontend Nginx
  frontend:
    container_name: pulse-frontend
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - inetum-network

  # Service Backend Spring Boot
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: inetum-backend
    ports:
      - "8087:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:inetumdb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - inetum-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

networks:
  inetum-network:
    driver: bridge

volumes:
  h2-data: 