apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulse-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pulse-backend
  template:
    metadata:
      labels:
        app: pulse-backend
    spec:
      containers:
        - name: pulse-backend
          image: inetumreg.azurecr.io/pulse-backend:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: pulse-backend-service
spec:
  selector:
    app: pulse-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
