apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulse-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pulse-frontend
  template:
    metadata:
      labels:
        app: pulse-frontend
    spec:
      containers:
        - name: pulse-frontend
          image: inetumreg.azurecr.io/pulse-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pulse-frontend-service
spec:
  selector:
    app: pulse-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
